### PR TITLE
update to board-olympus-panel.c

### PR DESCRIPTION
**Pull request by puskyer**
These changes fix a boot time issue identifiec by epinter. On my sons i use one setting and on mine the other. Go figure?

### CODE REVIEW

**Comment by puskyer** [comment]
This is for people that are compiling their own and having issues. Per epinter changes.
Anyone known why? Keep having to change it everytime i do a compile.

**Comment by epinter** [comment]
These parameters will solve the problems for every type of panel ? If not, this should be handled in userspace (/data/system/olympuspanel.cfg).

**Comment by puskyer** [comment]
when I compile a new rom with  CM10.1 updates and I do not make those changes then when flashing I get a blank screen.  So I can not change the file you mentioned.

are you saying I should then modify the rom image to change those parameters before flashing?

Sorry new to this, not a programmer just want to keep my cm10.1 up to date.

Hope this makes sense.

**Comment by epinter** [comment]
Please, take a look at http://www.linuxmobile.org/ (see comments for the build 2013-12-07).

**Comment by puskyer** [comment]
Thank you

Now I understand.

Cheers

**Pull request closed without merging**
